#spring.main.banner-mode=off
#logging.level.org.springframework=ERROR
server.port=8099
api.url=https://localhost:5045/api/
#fillclick.api.url=https://devfapi.alternard.com/api/
spring.main.web-application-type=servlet

spring.jpa.hibernate.ddl-auto=none

#spring.datasource.initialization-mode=always
spring.datasource.platform=postgres
#spring.datasource.url=jdbc:postgresql://134.122.123.72:5432/devfraga
spring.datasource.url=jdbc:postgresql://localhost:5432/yaque
spring.datasource.username=alterna
spring.datasource.password=a1234
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
logging.level.org.hibernate.SQL=off
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=off
#spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.jpa.open-in-view=false
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

mqtt.uri=tcp://localhost:1883
#mqtt.client-id=devfraga
mqtt.client-id=yaque
mqtt.max-reconnect-delay=10
mqtt.keep-alive-interval=60
mqtt.executor-service-timeout=10
mqtt.username=
mqtt.password=
